const seedCases = [
  { id: 'GRV-2409-018', subject: 'Broken water dispenser in Block B', category: 'Facilities & infrastructure', date: 'Sep 20, 2024', status: 'In progress', owner: 'School facilities' },
  { id: 'GRV-2409-011', subject: 'Request for additional science lab hours', category: 'Academic support', date: 'Sep 12, 2024', status: 'Resolved', owner: 'Academic office' },
  { id: 'GRV-2408-034', subject: 'Bus route timing clarification', category: 'Transport', date: 'Aug 28, 2024', status: 'Resolved', owner: 'Transport desk' }
];
const state = { cases: JSON.parse(localStorage.getItem('resolve-cases') || 'null') || seedCases, filter: 'all', role: 'Student', name: 'Aarav Sharma', initials: 'AS' };
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
function saveCases() { localStorage.setItem('resolve-cases', JSON.stringify(state.cases)); }
function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); window.setTimeout(() => toast.classList.remove('show'), 3000); }
function statusClass(status) { return status === 'Resolved' ? 'resolved' : status === 'Under review' ? 'review' : 'progress'; }
function renderRecent() { $('#recent-list').innerHTML = state.cases.slice(0, 3).map((item) => `<div class="activity-item"><span class="case-mark">▤</span><div><strong>${item.subject}</strong><small>${item.id} · ${item.date}</small></div><span class="status-pill ${statusClass(item.status)}">${item.status}</span></div>`).join(''); }
function renderCases() { const query = ($('#search-input')?.value || '').toLowerCase(); const filtered = state.cases.filter((item) => (state.filter === 'all' || item.status === state.filter) && `${item.id} ${item.subject}`.toLowerCase().includes(query)); $('#complaints-table').innerHTML = filtered.length ? filtered.map((item) => `<tr><td>${item.subject}<small>${item.id}</small></td><td>${item.category}</td><td>${item.date}</td><td><span class="status-pill ${statusClass(item.status)}">${item.status}</span></td><td>${item.owner}</td><td><button class="table-action" data-case="${item.id}">View</button></td></tr>`).join('') : '<tr><td colspan="6">No grievances match your search.</td></tr>'; }
function renderNotifications() { const notifications = [{ icon: '✓', title: 'Your grievance has been received', text: 'GRV-2409-018 is now under review by the school facilities team.', time: '2 hours ago', unread: true }, { icon: '↗', title: 'Grievance resolved', text: 'Your request for additional science lab hours was resolved.', time: 'Sep 17, 2024', unread: true }, { icon: '◷', title: 'A review is in progress', text: 'A school official has started reviewing your transport query.', time: 'Aug 30, 2024', unread: false }]; $('#notification-list').innerHTML = notifications.map((item) => `<article class="notification-item ${item.unread ? 'unread' : ''}"><span class="notification-icon">${item.icon}</span><div><strong>${item.title}</strong><p>${item.text}</p><time>${item.time}</time></div></article>`).join(''); }
function navigate() { const requested = window.location.hash.replace('#', '') || 'dashboard'; const view = document.querySelector(`#view-${requested}`) ? requested : 'dashboard'; $$('.view').forEach((item) => item.classList.toggle('active-view', item.id === `view-${view}`)); $$('.nav-item').forEach((item) => item.classList.toggle('active', item.dataset.view === view)); const titles = { dashboard: `Good morning, ${state.name.split(' ')[0]}`, complaints: 'My grievances', submit: 'Submit a grievance', notifications: 'Notifications', reports: 'Reports', help: 'Help centre' }; $('#page-title').textContent = titles[view]; window.scrollTo({ top: 0, behavior: 'smooth' }); }
function openRoleModal() { $('#role-modal').hidden = false; }
function closeRoleModal() { $('#role-modal').hidden = true; }
function setRole(button) { state.role = button.dataset.role; state.name = button.dataset.name; state.initials = button.dataset.initials; $('#profile-name').textContent = state.name; $('#profile-role').textContent = `${state.role} account`; $('#active-role').textContent = `${state.role} view`; $$('.user-avatar, .avatar').forEach((item) => item.textContent = state.initials); closeRoleModal(); showToast(`Switched to ${state.role} view`); }
$('#grievance-form').addEventListener('submit', (event) => { event.preventDefault(); const category = $('#category').value; const subject = $('#subject').value.trim(); const description = $('#description').value.trim(); if (!category || !subject || !description) return; const id = `GRV-${new Date().getFullYear().toString().slice(-2)}09-${String(state.cases.length + 19).padStart(3, '0')}`; state.cases.unshift({ id, subject, category, date: 'Sep 23, 2024', status: 'Under review', owner: 'Portal triage' }); saveCases(); renderRecent(); renderCases(); event.target.reset(); $('#char-count').textContent = '0 / 1000'; showToast(`Grievance ${id} submitted successfully`); window.location.hash = 'complaints'; });
$('#description').addEventListener('input', (event) => { $('#char-count').textContent = `${event.target.value.length} / 1000`; });
$('#search-input').addEventListener('input', renderCases);
$$('.filter-tab').forEach((button) => button.addEventListener('click', () => { state.filter = button.dataset.filter; $$('.filter-tab').forEach((item) => item.classList.toggle('active', item === button)); renderCases(); }));
$('#role-switcher').addEventListener('click', openRoleModal); $('#close-modal').addEventListener('click', closeRoleModal); $('#role-modal').addEventListener('click', (event) => { if (event.target === $('#role-modal')) closeRoleModal(); }); $$('.role-options button').forEach((button) => button.addEventListener('click', () => setRole(button)));
$('#mark-read').addEventListener('click', () => { $$('.notification-item').forEach((item) => item.classList.remove('unread')); $('.alert-count').textContent = '0'; showToast('All notifications marked as read'); });
$('#export-report').addEventListener('click', () => showToast('Report prepared for download'));
$('#theme-toggle').addEventListener('click', () => document.body.classList.toggle('soft-theme'));
document.addEventListener('click', (event) => { const link = event.target.closest('[data-view-link]'); if (link) window.location.hash = link.dataset.viewLink; const action = event.target.closest('[data-case]'); if (action) showToast(`Opening ${action.dataset.case}`); });
window.addEventListener('hashchange', navigate); renderRecent(); renderCases(); renderNotifications(); navigate();
